apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        inservice: api-service
    spec:
      containers:
      - name: api
        image: api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "S3cur3P@ssW0rd!"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 10 
          periodSeconds: 5        
          successThreshold: 1     
          failureThreshold: 3     
      restartPolicy: Always 