apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
    inservice: api-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001