version: '3.4'

networks:
  user-testing:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - user-testing
    depends_on:
      - ms-db

  ms-db:
    container_name: us-ms-sql
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      - user-testing

