apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: sql
    inservice: sql-service
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: LoadBalancer