// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserTesting.DAL.Data;

#nullable disable

namespace UserTesting.DAL.Migrations
{
    [DbContext(typeof(UserTestingDbContext))]
    [Migration("20231016205842_AddSeeding")]
    partial class AddSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d96d22fd-fbe0-4ba1-a8d0-7f076c3e3edd",
                            ConcurrencyStamp = "d96d22fd-fbe0-4ba1-a8d0-7f076c3e3edd",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11bac029-c18b-40dd-baca-2854e731149f",
                            RoleId = "d96d22fd-fbe0-4ba1-a8d0-7f076c3e3edd"
                        },
                        new
                        {
                            UserId = "bf97c9eb-46e2-487e-9bd8-b0ec737a90e9",
                            RoleId = "d96d22fd-fbe0-4ba1-a8d0-7f076c3e3edd"
                        },
                        new
                        {
                            UserId = "146df55d-308b-4846-91b7-d5725b8c6045",
                            RoleId = "d96d22fd-fbe0-4ba1-a8d0-7f076c3e3edd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba4dfdda-e505-402e-8be2-d2c619974c9e"),
                            Description = "This is Test 1",
                            Name = "Test 1",
                            Questions = "[{\"Ordinal\":1,\"Text\":\"Question 1\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":2,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":1,\"Text\":\"Option 1\"}},{\"Ordinal\":2,\"Text\":\"Question 2\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":2,\"Text\":\"Option 2\"}},{\"Ordinal\":3,\"Text\":\"Question 3\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":3,\"Text\":\"Option 3\"}}]"
                        },
                        new
                        {
                            Id = new Guid("2cbae21d-0651-4609-b77c-a0d69af10349"),
                            Description = "This is Test 2",
                            Name = "Test 2",
                            Questions = "[{\"Ordinal\":1,\"Text\":\"Question 1\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":2,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":1,\"Text\":\"Option 1\"}},{\"Ordinal\":2,\"Text\":\"Question 2\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":2,\"Text\":\"Option 2\"}},{\"Ordinal\":3,\"Text\":\"Question 3\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":3,\"Text\":\"Option 3\"}}]"
                        },
                        new
                        {
                            Id = new Guid("591928f1-0e0a-4e7b-8b9d-e5c7a7791974"),
                            Description = "This is Test 3",
                            Name = "Test 3",
                            Questions = "[{\"Ordinal\":1,\"Text\":\"Question 1\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":2,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":1,\"Text\":\"Option 1\"}},{\"Ordinal\":2,\"Text\":\"Question 2\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":2,\"Text\":\"Option 2\"}},{\"Ordinal\":3,\"Text\":\"Question 3\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":3,\"Text\":\"Option 3\"}}]"
                        },
                        new
                        {
                            Id = new Guid("0ccda22e-372a-48ef-afc6-9dc8b41007e1"),
                            Description = "This is Test 4",
                            Name = "Test 4",
                            Questions = "[{\"Ordinal\":1,\"Text\":\"Question 1\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":2,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":1,\"Text\":\"Option 1\"}},{\"Ordinal\":2,\"Text\":\"Question 2\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":2,\"Text\":\"Option 2\"}},{\"Ordinal\":3,\"Text\":\"Question 3\",\"Options\":[{\"Ordinal\":1,\"Text\":\"Option 1\"},{\"Ordinal\":2,\"Text\":\"Option 2\"},{\"Ordinal\":3,\"Text\":\"Option 3\"}],\"Answer\":{\"Ordinal\":3,\"Text\":\"Option 3\"}}]"
                        });
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11bac029-c18b-40dd-baca-2854e731149f",
                            ConcurrencyStamp = "8a8f62f8-5980-4129-8faf-213f587c6ccb",
                            Email = "user1@example.com",
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEMWE7SvfhKRPgZd2RfUAanT03ddPzg8OMjDLFTlZUd0TjQhmujAYHPzSgOzq1yIY4w==",
                            SecurityStamp = "f8d45684-76f4-4549-845c-5f7bcd00bde0",
                            UserName = "User1"
                        },
                        new
                        {
                            Id = "bf97c9eb-46e2-487e-9bd8-b0ec737a90e9",
                            ConcurrencyStamp = "a5a75308-996d-4a7b-9abb-3e69acf3aa35",
                            Email = "user2@example.com",
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEFk2wFG4NK1kL/2qQhkj2bvtZcI4yZ2bzYzaOVeQ3eUC2tj/inLDTvqSsqb6sll+Iw==",
                            SecurityStamp = "1163ecd5-da4a-4642-85bc-1497e5eb6e28",
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "146df55d-308b-4846-91b7-d5725b8c6045",
                            ConcurrencyStamp = "32f1b2c0-f313-42ca-a797-3013df971d99",
                            Email = "user3@example.com",
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAELFGBsswSAhh5+nqktf4LVW3qQhCi0U5iehKwpycyVADqNjQTiogzVYeld00IrhbVQ==",
                            SecurityStamp = "a786cb67-d813-40d8-8844-2bcb2989915d",
                            UserName = "User3"
                        });
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.UserTest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Mark")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("UserTests");

                    b.HasData(
                        new
                        {
                            UserId = "11bac029-c18b-40dd-baca-2854e731149f",
                            TestId = new Guid("ba4dfdda-e505-402e-8be2-d2c619974c9e"),
                            Mark = 0.8m,
                            Passed = true
                        },
                        new
                        {
                            UserId = "11bac029-c18b-40dd-baca-2854e731149f",
                            TestId = new Guid("2cbae21d-0651-4609-b77c-a0d69af10349"),
                            Mark = 0.3m,
                            Passed = true
                        },
                        new
                        {
                            UserId = "11bac029-c18b-40dd-baca-2854e731149f",
                            TestId = new Guid("591928f1-0e0a-4e7b-8b9d-e5c7a7791974"),
                            Passed = false
                        },
                        new
                        {
                            UserId = "bf97c9eb-46e2-487e-9bd8-b0ec737a90e9",
                            TestId = new Guid("591928f1-0e0a-4e7b-8b9d-e5c7a7791974"),
                            Passed = false
                        },
                        new
                        {
                            UserId = "bf97c9eb-46e2-487e-9bd8-b0ec737a90e9",
                            TestId = new Guid("0ccda22e-372a-48ef-afc6-9dc8b41007e1"),
                            Passed = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UserTesting.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UserTesting.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserTesting.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UserTesting.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.UserTest", b =>
                {
                    b.HasOne("UserTesting.DAL.Entities.Test", "Test")
                        .WithMany("UserTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserTesting.DAL.Entities.User", "User")
                        .WithMany("UserTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.Test", b =>
                {
                    b.Navigation("UserTests");
                });

            modelBuilder.Entity("UserTesting.DAL.Entities.User", b =>
                {
                    b.Navigation("UserTests");
                });
#pragma warning restore 612, 618
        }
    }
}
